[package]
name = "gql_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.14"
miette = { version = "7", features = ["fancy"] }
smol_str = "0.3"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "parser_benchmarks"
harness = false
